CREATE TABLE "GCG_4391_ContSubProg"(
 "Submittal_Package" DATE,
 "Package_Review" DATE,
 "Receive_Approval" DATE,
 "Review_Job" BIT NOT NULL ,
 "Develop_Project" BIT NOT NULL ,
 "ProjectPlan_Customer" BIT NOT NULL ,
 "Complete_RD" VARCHAR(4),
 "Complete_PLC" VARCHAR(4),
 "Complete_SCADA" VARCHAR(4),
 "List_Parts" BIT NOT NULL ,
 "Punch_List" BIT NOT NULL ,
 "Document_Pump" BIT NOT NULL ,
 "Complete_Drawing" BIT NOT NULL ,
 "Invoice_Total" BIT NOT NULL ,
 "Customer_Training" BIT NOT NULL ,
 "Review_Customer" BIT NOT NULL ,
 "Develope_Custom" BIT NOT NULL ,
 "Final_Punch" DATE,
 "ReviewPunch_List" DATE,
 "Approved_Punch" DATE,
 "Submit_Programming" BIT NOT NULL ,
 "Provide_Customer_OM" BIT NOT NULL ,
 "Provide_Customer" BIT NOT NULL ,
 "Save_Files" BIT NOT NULL ,
 "Save_Project" BIT NOT NULL ,
 "PunchList_Complete" DATE,
 "Project_Audit" BIT NOT NULL ,
 "Project_Closeout" BIT NOT NULL ,
 "Submit_Customer" BIT NOT NULL ,
 "SO" CHAR(9) NOT NULL ,
 "So_Ln" CHAR(4) NOT NULL ,
 PRIMARY KEY ("SO", "So_Ln"));
