CREATE TABLE "GCG_4391_WFDashboard"(
 "Est_Quote" BIT NOT NULL ,
 "Sales_Order" CHAR(9) NOT NULL ,
 "Disassembly" VARCHAR(20),
 "Firm_Quote_Req" BIT NOT NULL ,
 "Quote_New_Sub" VARCHAR(8),
 "Quote_New_Eng" VARCHAR(8),
 "Bond_Job_5K" VARCHAR(8),
 "Send_TY_5K" VARCHAR(8),
 "Order_Parts" BIT NOT NULL ,
 "Routing" VARCHAR(20),
 "Machining" VARCHAR(20),
 "Assembly" VARCHAR(20),
 "Shipper" BIT NOT NULL ,
 "Request_F5_Invoice" BIT NOT NULL ,
 "As_Shipped_Report" BIT NOT NULL ,
 "Invoice" BIT NOT NULL ,
 "Notes" VARCHAR(400),
 "Sales_Line" CHAR(4) NOT NULL ,
 "UpdateBOM1_DT" DATE,
 "PartsDue" DATE,
 "FS_Scheduled" VARCHAR(10),
 PRIMARY KEY ("Sales_Order", "Sales_Line"));
