CREATE TABLE "GCG_4391_ISSQOSO"(
 "SO" CHAR(9) NOT NULL ,
 "SO_Ln" CHAR(4) NOT NULL ,
 "RFQ_Received" DATE,
 "IsBid_Quote" BIT NOT NULL ,
 "FS_RFQ" VARCHAR(3),
 "Controls_RFQ" VARCHAR(3),
 "SendOut_Pricing" BIT NOT NULL ,
 "Follow_up" DATE,
 "Double_CheckSheet" VARCHAR(10),
 "Router_Worksheet" BIT NOT NULL ,
 "Quote_Approval_10k" BIT NOT NULL ,
 "Quote_Sent" DATE,
 "Customer_Approval" DATE,
 "IsBid_SO" BIT NOT NULL ,
 "Create_SO" BIT NOT NULL ,
 "Send_OrderAck" DATE,
 "Prepare_PhysicalFile" BIT NOT NULL ,
 "PO_TCNeeded" VARCHAR(3),
 "Invoice_CutoffDT" DATE,
 "Issue_Material" BIT NOT NULL ,
 "Order_Parts" DATE,
 "Verify_ShipSchedule" BIT NOT NULL ,
 "Shipper" BIT NOT NULL ,
 "BOM" DATE,
 "NOTES" VARCHAR(400),
 "Create_Quote" DATE,
 "Bid_DueDate" DATE,
 PRIMARY KEY ("SO", "SO_Ln"));
