CREATE TABLE "GCG_4391_BIDSO"(
 "SO" CHAR(9) NOT NULL ,
 "SO_Ln" CHAR(4) NOT NULL ,
 "Send_OrderAck" DATE,
 "HFAPO_Request" BIT NOT NULL ,
 "Submittals_Approval" DATE,
 "Send_Customer" BIT NOT NULL ,
 "Follow_Bond" DATE,
 "Confirm_Receipt" DATE,
 "SubmittalFU_DT" DATE,
 "Revise_Submittal" BIT NOT NULL ,
 "Approval_Submitted" BIT NOT NULL ,
 "Release_HFAPO" BIT NOT NULL ,
 "Notice_Furnishing" DATE,
 "Prevenative_Maint" DATE,
 "O_M" DATE,
 "Send_FSRequest" DATE,
 "Worsheet_Rev" DATE,
 PRIMARY KEY ("SO", "SO_Ln"));
