CREATE TABLE "GCG_4391_CONTROL"(
 "Request_Received" DATE,
 "Walk_requied" VARCHAR(3),
 "Walk_Complete" VARCHAR(3),
 "Define_Job" BIT NOT NULL ,
 "Quote_RequiredCO" BIT NOT NULL ,
 "Create_SO" BIT NOT NULL ,
 "Create_WO" BIT NOT NULL ,
 "KISM_job" VARCHAR(3),
 "StartUpJob" BIT NOT NULL ,
 "Job_complete" BIT NOT NULL ,
 "RGA" BIT NOT NULL ,
 "Controls_Engineer" BIT NOT NULL ,
 "PartsNeeded_Cont" BIT NOT NULL ,
 "Controls_Programming" BIT NOT NULL ,
 "Reconfirm_Customer" BIT NOT NULL ,
 "Schedule_Contractor" BIT NOT NULL ,
 "Prepare_ServerFile" BIT NOT NULL ,
 "Process_WO" BIT NOT NULL ,
 "Invoice" BIT NOT NULL ,
 "Notes" VARCHAR(300),
 "SO" CHAR(9) NOT NULL ,
 "So_Ln" CHAR(4) NOT NULL ,
 "Email_Customer" VARCHAR(3),
 PRIMARY KEY ("SO", "So_Ln"));
